
title: Chris Mangum - Portfolio
author: Chris Mangum
email: csmangum@gmail.com
description: Personal website for Chris Mangum
url: "https://csmangum.github.io"
twitter_username: peril10
github_username:  csmangum
google_analytics: UA-32516552-2
